### PR TITLE
Enhanced pkgdown setup (#54)

### PR DESCRIPTION
**Pull request by sdhutchins**
- Reordered `NEWS.md` so that most recent news is first.
- Added an authors section to `_pkgdown.yml`
- Fixed broken crayon imports.
- Added custom css stylesheet.

### CODE REVIEW

**Comment by sdhutchins** [comment]
@grabear I didn't rebuild the pkgdown site (i'll let you do that).

I added a shell vignette - just for the sake of the _pkgdown.yml file.

There's so much more we can add, and I know you have a few vignettes going so I think it's going to look great. Let me know what you think of the theme. There are a couple of things I want to tweak with it, but I like it.

**Comment by grabear** [comment]
Nice!  Alright I'll let you know.  I'm going to merge this in a few minutes, and then I will make a quick PR with my vignettes.

**Comment by sdhutchins** [comment]
Look...the WIP prevents a merge (I think)! lol Okay, I'll remove that once the build has passed.

**Comment by grabear** [comment]
> Look...the WIP prevents a merge (I think)! lol Okay, I'll remove that once the build has passed.

Lol what the heck..  It looks fine now.  I didn't see that.

**Comment by sdhutchins** [comment]
> > Look...the WIP prevents a merge (I think)! lol Okay, I'll remove that once the build has passed.
> 
> Lol what the heck.. It looks fine now. I didn't see that.

LOL if you add `WIP` to the PR title, it won't allow it to be merged.

**Pull request merged**
