### PR TITLE
Removed duplicate microbiome in DESCRIPTION

### PR DESCRIPTION
**Pull request by sdhutchins**
The build is failing in the dev-master because of the `microbiome` package. This should fix it.

### CODE REVIEW

**Comment by sdhutchins** [comment]
> We're going to have some fun merge conflicts later this week lol.
> [MicrobiomeR/DESCRIPTION](https://github.com/vallenderlab/MicrobiomeR/blob/0dda5279933e791fcb8e390c88545e459004659f/DESCRIPTION#L18)
> 
> Line 18 in [0dda527](/vallenderlab/MicrobiomeR/commit/0dda5279933e791fcb8e390c88545e459004659f)
> 
>  github::microbiome/microbiome

So I'm taking it off the github version because of some issues I had with that. Want to keep it at a specified version so it won't break again.

**Comment by sdhutchins** [comment]
> Add this to the remotes @sdhutchins :
> `github::microbiome/microbiome`
> 
> I made a PR to the master branch of `microbiome` so that the builds work properly for multiple version of R instead of just R3.5.3 or whatever the latest one is.

That wasn't what was breaking this week. They changed function names.

**Comment by grabear** [comment]
We're going to have some fun merge conflicts later this week lol

> > Add this to the remotes @sdhutchins :
> > `github::microbiome/microbiome`
> > I made a PR to the master branch of `microbiome` so that the builds work properly for multiple version of R instead of just R3.5.3 or whatever the latest one is.
> 
> That wasn't what was breaking this week. They changed function names.

:crying_cat_face: good times....

**Comment by sdhutchins** [comment]
> **We're going to have some fun merge conflicts later this week lol**
> 
> > > Add this to the remotes @sdhutchins :
> > > `github::microbiome/microbiome`
> > > I made a PR to the master branch of `microbiome` so that the builds work properly for multiple version of R instead of just R3.5.3 or whatever the latest one is.
> > 
> > 
> > That wasn't what was breaking this week. They changed function names.
> 
>  good times....

lol what is this in reference to?

**Comment by sdhutchins** [comment]
This should be addressed in commit https://github.com/vallenderlab/MicrobiomeR/pull/73/commits/b1c020fad8831fa97366a4d59767eb48ea00ea9d

**Pull request closed without merging**
