### PR TITLE
Update dev-master to master.

### PR DESCRIPTION
**Pull request by sdhutchins**

### CODE REVIEW

**Comment by sdhutchins** [comment]
> I'm going to hold off to see if we can get #79 merged into dev-master first.

This is just updating dev-master to master. It might break if not merged before.

**Comment by grabear** [comment]
Are you sure?  #79 is the Joss branch which is forked from the dev-master.

**Comment by sdhutchins** [comment]
Yes. The dev master wasnt up to date with master.

**Comment by grabear** [comment]
> Yes. The dev master wasnt up to date with master.

In my head, I thought we were updating master with dev-master......

**Pull request merged**
