### PR TITLE
Improve docs and fix spelling errors (#88).

### PR DESCRIPTION
**Pull request by sdhutchins**
Updated master.

### CODE REVIEW

**Comment by sdhutchins** [comment]
*ping* @grabear

**Comment by grabear** [comment]
Is the branch Build Error an issue @sdhutchins?

**Comment by sdhutchins** [comment]
> Can you update the `ordination_plot` documentation as well?

I'm working on that in another branch because I also need to change something internally with the alpha diversity plots.

**Comment by sdhutchins** [comment]
noooo lol

**Pull request merged**
