### PR TITLE
Joss branch

### PR DESCRIPTION
**Pull request by grabear**
# MicrobiomeR 0.5.0

* Added the JOSS paper and draft vignette
* Changed correlation plots
  * Removed color from background
  * Removed hard coded plot limits
  * Added "1:1" line and Average lines
  * Added a `trans` parameter to transform the x and y axis
* Changed function names
  * From `create_metacoder` to `create_taxmap`
  * From `agglomerate_metacoder` to `agglomerate_taxmap`
  * From `melt_metacoder` to `melt_taxmap`
* Bugs
  * Fixed `output_dir` bug where error should have been a warning
  * Fixed correlation plot bug where treatments were on the wrong axis.
  * Fixed output message for heat tree plots.

### CODE REVIEW

**Comment by grabear** [comment]
@sdhutchins Working on fixing `devtools::check()` Notes, Warnings, and Errors.

**Comment by sdhutchins** [comment]
I'm guessing some parameter is off in the `analysis.Rmd` vignette after the changes you made. @grabear

**Comment by grabear** [comment]
> I'm guessing some parameter is off in the `analysis.Rmd` vignette after the changes you made. @grabear

Yea..  I was too tired last night, but I may have figured it out.  Fingers crossed

**Comment by grabear** [comment]
I forgot to rebuild the package after that last commit.  So after I rebuild hopefully things work out.

**Comment by sdhutchins** [comment]
```console
- Session info --------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Chicago             
 date     2019-02-20                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package      * version    date       lib source                                   
 ade4           1.7-13     2018-08-31 [1] CRAN (R 3.5.1)                           
 ape            5.2        2018-09-24 [1] CRAN (R 3.5.1)                           
 assertthat     0.2.0      2017-04-11 [1] CRAN (R 3.5.1)                           
 backports      1.1.3      2018-12-14 [1] CRAN (R 3.5.1)                           
 Biobase        2.42.0     2018-10-30 [1] Bioconductor                             
 BiocGenerics   0.28.0     2018-10-30 [1] Bioconductor                             
 biomformat     1.10.0     2018-10-30 [1] Bioconductor                             
 Biostrings     2.50.1     2018-11-06 [1] Bioconductor                             
 callr          3.1.1      2018-12-21 [1] CRAN (R 3.5.2)                           
 cli            1.0.1      2018-09-25 [1] CRAN (R 3.5.1)                           
 cluster        2.0.7-1    2018-04-13 [2] CRAN (R 3.5.1)                           
 codetools      0.2-15     2016-10-05 [2] CRAN (R 3.5.1)                           
 colorspace     1.4-0      2019-01-13 [1] CRAN (R 3.5.2)                           
 crayon         1.3.4      2019-01-08 [1] Github (r-lib/crayon@74bee76)            
 curl           3.3        2019-01-10 [1] CRAN (R 3.5.2)                           
 data.table     1.12.0     2019-01-13 [1] CRAN (R 3.5.2)                           
 desc           1.2.0      2018-05-01 [1] CRAN (R 3.5.1)                           
 devtools       2.0.1      2018-10-26 [1] CRAN (R 3.5.1)                           
 digest         0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                           
 diptest        0.75-7     2016-12-05 [1] CRAN (R 3.5.0)                           
 dplyr          0.8.0.1    2019-02-15 [1] CRAN (R 3.5.2)                           
 evaluate       0.13       2019-02-12 [1] CRAN (R 3.5.2)                           
 fansi          0.4.0      2018-10-05 [1] CRAN (R 3.5.1)                           
 forcats        0.4.0      2019-02-17 [1] CRAN (R 3.5.2)                           
 foreach        1.4.4      2017-12-12 [1] CRAN (R 3.5.1)                           
 fs             1.2.6      2018-08-23 [1] CRAN (R 3.5.1)                           
 ggplot2      * 3.1.0      2018-10-25 [1] CRAN (R 3.5.1)                           
 ggpubr       * 0.2.999    2018-12-06 [1] Github (kassambara/ggpubr@de26170)       
 ggrepel        0.8.0      2018-05-09 [1] CRAN (R 3.5.1)                           
 ggsignif       0.5.0      2019-02-20 [1] CRAN (R 3.5.1)                           
 ggthemes       4.1.0      2019-02-19 [1] CRAN (R 3.5.1)                           
 glue           1.3.0.9000 2019-01-26 [1] Github (tidyverse/glue@a1143f7)          
 gridExtra      2.3        2017-09-09 [1] CRAN (R 3.5.1)                           
 gtable         0.2.0      2016-02-26 [1] CRAN (R 3.5.1)                           
 hms            0.4.2      2018-03-10 [1] CRAN (R 3.5.1)                           
 htmltools      0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                           
 httr           1.4.0      2018-12-11 [1] CRAN (R 3.5.2)                           
 igraph         1.2.4      2019-02-13 [1] CRAN (R 3.5.2)                           
 IRanges        2.16.0     2018-10-30 [1] Bioconductor                             
 iterators      1.0.10     2018-07-13 [1] CRAN (R 3.5.1)                           
 jsonlite       1.6        2018-12-07 [1] CRAN (R 3.5.1)                           
 kableExtra     1.0.1      2019-01-22 [1] CRAN (R 3.5.2)                           
 knitr          1.21       2018-12-10 [1] CRAN (R 3.5.1)                           
 labeling       0.3        2014-08-23 [1] CRAN (R 3.5.0)                           
 lattice        0.20-35    2017-03-25 [2] CRAN (R 3.5.1)                           
 lazyeval       0.2.1      2017-10-29 [1] CRAN (R 3.5.1)                           
 magrittr     * 1.5        2014-11-22 [1] CRAN (R 3.5.1)                           
 MASS           7.3-50     2018-04-30 [2] CRAN (R 3.5.1)                           
 Matrix         1.2-14     2018-04-13 [2] CRAN (R 3.5.1)                           
 memoise        1.1.0      2017-04-21 [1] CRAN (R 3.5.1)                           
 metacoder      0.3.1      2019-01-04 [1] CRAN (R 3.5.2)                           
 mgcv           1.8-24     2018-06-23 [2] CRAN (R 3.5.1)                           
 microbiome     1.5.27     2019-02-11 [1] Github (microbiome/microbiome@db93d7a)   
 MicrobiomeR  * 0.4.1      2019-02-20 [1] Github (vallenderlab/MicrobiomeR@095a03c)
 modes          0.7.0      2016-03-07 [1] CRAN (R 3.5.0)                           
 multtest       2.38.0     2018-10-30 [1] Bioconductor                             
 munsell        0.5.0      2018-06-12 [1] CRAN (R 3.5.1)                           
 nlme           3.1-137    2018-04-07 [2] CRAN (R 3.5.1)                           
 permute        0.9-4      2016-09-09 [1] CRAN (R 3.5.1)                           
 phyloseq     * 1.25.2     2018-12-03 [1] Github (joey711/phyloseq@cd7da46)        
 pillar         1.3.1      2018-12-15 [1] CRAN (R 3.5.1)                           
 pkgbuild       1.0.2      2018-10-16 [1] CRAN (R 3.5.1)                           
 pkgconfig      2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                           
 pkgload        1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                           
 plyr           1.8.4      2016-06-08 [1] CRAN (R 3.5.1)                           
 prettyunits    1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                           
 processx       3.2.1      2018-12-05 [1] CRAN (R 3.5.1)                           
 ps             1.3.0      2018-12-21 [1] CRAN (R 3.5.2)                           
 purrr          0.3.0      2019-01-27 [1] CRAN (R 3.5.2)                           
 R6             2.4.0      2019-02-14 [1] CRAN (R 3.5.2)                           
 Rcpp           1.0.0      2018-11-07 [1] CRAN (R 3.5.1)                           
 readr          1.3.1      2018-12-21 [1] CRAN (R 3.5.2)                           
 remotes        2.0.2      2018-10-30 [1] CRAN (R 3.5.1)                           
 reshape2       1.4.3      2017-12-11 [1] CRAN (R 3.5.1)                           
 rhdf5          2.26.0     2018-10-30 [1] Bioconductor                             
 Rhdf5lib       1.4.1      2018-11-22 [1] Bioconductor                             
 rlang          0.3.1      2019-01-08 [1] CRAN (R 3.5.1)                           
 rmarkdown      1.11       2018-12-08 [1] CRAN (R 3.5.1)                           
 rprojroot      1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                           
 rstudioapi     0.9.0      2019-01-12 [1] Github (rstudio/rstudioapi@aa6cdb0)      
 Rtsne          0.15       2018-11-10 [1] CRAN (R 3.5.1)                           
 rvest          0.3.2      2016-06-17 [1] CRAN (R 3.5.1)                           
 S4Vectors      0.20.1     2018-11-09 [1] Bioconductor                             
 scales         1.0.0      2018-08-09 [1] CRAN (R 3.5.1)                           
 scico          1.1.0      2018-11-20 [1] CRAN (R 3.5.1)                           
 sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 3.5.1)                           
 shades       * 1.3.1      2019-02-12 [1] Github (jonclayden/shades@b1ac3e5)       
 stringi        1.3.1      2019-02-13 [1] CRAN (R 3.5.2)                           
 stringr        1.4.0      2019-02-10 [1] CRAN (R 3.5.2)                           
 survival       2.42-3     2018-04-16 [2] CRAN (R 3.5.1)                           
 taxa           0.3.2      2019-01-02 [1] CRAN (R 3.5.1)                           
 testthat       2.0.1      2018-10-13 [1] CRAN (R 3.5.1)                           
 tibble         2.0.1      2019-01-12 [1] CRAN (R 3.5.2)                           
 tidyr          0.8.2      2018-10-28 [1] CRAN (R 3.5.1)                           
 tidyselect     0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                           
 usethis        1.4.0      2018-08-14 [1] CRAN (R 3.5.1)                           
 utf8           1.1.4      2018-05-24 [1] CRAN (R 3.5.1)                           
 vegan          2.5-4      2019-02-04 [1] CRAN (R 3.5.2)                           
 viridis        0.5.1      2018-03-29 [1] CRAN (R 3.5.1)                           
 viridisLite    0.3.0      2018-02-01 [1] CRAN (R 3.5.1)                           
 webshot        0.5.1      2018-09-28 [1] CRAN (R 3.5.1)                           
 withr          2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                           
 xfun           0.4        2018-10-23 [1] CRAN (R 3.5.1)                           
 xml2           1.2.0      2018-01-24 [1] CRAN (R 3.5.1)                           
 XVector        0.22.0     2018-10-30 [1] Bioconductor                             
 zlibbioc       1.28.0     2018-10-30 [1] Bioconductor                             

[1] C:/Users/shutchins2/Documents/R/win-library/3.5
[2] C:/Program Files/R/R-3.5.1/library
```

**Comment by grabear** [comment]
@sdhutchins Thoughts?

**Comment by sdhutchins** [comment]
After your tweet, it may be best to find whatever bug was introduced by `dplyr`.

**Comment by grabear** [comment]
dplyr also relies on the new (Feb 4th) purr 0.3.0

**Comment by grabear** [comment]
https://github.com/tidyverse/googlesheets4/commit/e0f9eca939eb0a756003b03106b108edf1a82b0c

**Comment by grabear** [comment]
Not sure if that's significant

**Comment by grabear** [comment]
I'm going to resolve the conflicts introduced from #83 and then try to merge.  I will also rebuild the docs @sdhutchins

**Comment by grabear** [comment]
Closing this branch to fix conflicts and to update the paper.

**Pull request closed without merging**
